### ISSUE TITLE
Future roadmap: Internationalization, TypeScript, responsive design and performance!

### ISSUE THREAD

**Issue by retrixe** [RSG-Group/website#12]
So, our website is on its way to acing Lighthouse, and we want to make this site, while not popular, a baseline for other applications. So I've decided to release our future plans for RSG-Group/website.

- [ ] Switch to TypeScript.
- [ ] Internationalization makes life good.
- [ ] Performance and optimization is compulsory.
- [ ] Make cards the same size on all platforms.

**Comment by radi-cho** [comment]
cool

**Comment by retrixe** [comment]
Newer beta releases of material-ui do not support SSR very well, and we suffer significant performance loss. Removal of Material UI should be high priority for the October release, and should make the cut by then. PostCSS and the rest can wait till November if we are not done with them by then.

**Comment by retrixe** [comment]
Work for task 1 done in 8ba1316.

**Comment by radi-cho** [comment]
### What about adding Google Analytics to our website?

**Comment by retrixe** [comment]
Google Analytics.. well.. really. It can be put up for debate.. but well..

**Comment by retrixe** [comment]
@radi-cho, do something. Can you try moving the buttons in the cards to the bottom? buttonSpacing isn't very responsive on HiDPi displays, which are like, everywhere nowadays. You know CSS, keep them 10px from the bottom of the card, or some reasonable space that when you press and hold the button, the ripple is a couple pixels from the bottom. Regular positioning isn't working and I don't have time for math. This is the last thing to do before I begin the switch to Koa.

**Comment by suhail-ansari-apconic** [comment]
I'm grounded lol

I'm planning to move hosting to Google Cloud Platform or Amazon Web Services when I'm back. I have a debit card

**Comment by retrixe** [comment]
I'm unavailable till the 26th and we will only have 5 days to finish work on responsive design, and that is during my exams.
-.-

I have added some items to the roadmap.

**Comment by radi-cho** [comment]
@retrixe checkout #14

**Comment by retrixe** [comment]
Yes, October 2017 Release brings many solutions to this.
Want to fix some responsiveness issues though.

**Comment by retrixe** [comment]
Seems all good.. Want to test on a device with 18:9 ratio though e.g. Galaxy S8. I know someone who has one, but he'll come by on Monday so.. yeah.

**Comment by retrixe** [comment]
Looks fine. Will deploy soon.

**Comment by retrixe** [comment]
Deployed November 2017 release. December 2017 release will finish this off.

**Comment by radi-cho** [comment]
Well... This needs to be done. We need to publish a release this month. We was thinking for `New Year Release` the last time... now... `Summer release`.... lol

**Comment by retrixe** [comment]
Performance and optimization is being worked on. Much less dependencies, added some suggestions.

**Comment by retrixe** [comment]
Currently, we are going to launch one last release from this outdated codebase, by January end optimistically. After this, we are proceeding with a complete rewrite from scratch, with only Next.js and React, or with a potential Vue.js version.

Planned features:
Open Graph Protocol support, less progressive web app and more performance. Remove custom server and Express and update dependencies. Fixed styles (ref broken test pilot version in master) and Material UI 1.0 along with updated React and Next.js versions.
